plan/plan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    
]

plan/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_task, name='add_task'),
]

plan/tasks/models.py
from django.db import models

# Create your models here.

plan/tasks/views.py
from django.shortcuts import render, redirect
from django.http import request
from django import forms

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# Create your views here.
def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []
        
    return render(request, "tasks/task_list.html", { 'tasks': request.session['tasks'] })

def add_task(request):
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            update_task = request.session['tasks']
            update_task.append(task)
            request.session['tasks'] = update_task
            return redirect("tasks:index")
        else:
            return render(request, "tasks/add_task.html", { 'form': form })

    return render(request, "tasks/add_task.html", 
                  {
                    'form': NewTaskForm(),
                  },
                )

plan/tasks/templates/tasks/add_task.html
{% extends "tasks/master.html" %}

{% block Title %} Add-Task {% endblock Title %}

{% block content %}
    <h1>Create a Task</h1>
    <form action="{% url 'tasks:add_task' %}" method='post'>
        {% csrf_token %}
        {{ form }}
        <button type="Submit" >
            Submit
        </button>
    </form>

    <a href="{% url 'tasks:index' %}" class="back-link"> All Tasks </a>
{% endblock content %}

plan/tasks/templates/tasks/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

plan/tasks/templates/tasks/task_list.html
{% extends "tasks/master.html" %}

{% block title %} All tasks {% endblock title %}

{% block content %}
    <h1>Welcome!</h1>
    <h2>Here are your tasks😊</h2>
    <ul>
        {% for task in tasks %}
            <li> {{ task }} </li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add_task' %}" class="back-link">Add New Task</a>
{% endblock content %}